import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import FloatingNav from "./components/FloatingNav";
import Scroll from "./components/ScrollToTop";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
    title: "David Lee | Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${inter.variable}`}>
            <head>
                <link rel="icon" href="/favicon.webp" />
            </head>
            <Scroll />
            <body className="relative min-h-screen flex flex-col justify-between">
                <div className="absolute -z-50 top-0 left-0 w-full h-screen bg-gradient-to-b md:bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-csWhite/10 via-csBlack/10 to-csBlack bg-no-repeat"></div>
                <FloatingNav />
                <Header />
                <main className="customPadding">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
